dir                     = /PATH/TO/ocsp-stapling/demoCA

[ server ]
default_server          = wildfly

[ wildfly ]
certificate             = $dir/server.crt
database                = $dir/index.txt
new_certs_dir           = $dir/newcerts
private_key             = $dir/server.keystore
serial                  = $dir/serial

default_crl_days        = 365
default_days            = 3650
default_md              = sha256

policy                  = wildfly_policy
x509_extensions         = v3_req

email_in_dn             = no

[ req ]
distinguished_name      = req_distinguished_name
req_extensions          = v3_req
prompt                  = no
default_bits            = 2048
default_md              = sha256
default_keyfile         = server.keystore
x509_extensions         = v3_req

[ req_distinguished_name ]
commonName              = wildfly
stateOrProvinceName     = ON
countryName             = CA
organizationName        = elytron

[ wildfly_policy ]
countryName             = optional
stateOrProvinceName     = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ v3_req ]
authorityInfoAccess     = OCSP;URI:http://127.0.0.1:10000
basicConstraints        = CA:FALSE
keyUsage                = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage        = OCSPSigning
